# Generated by Django 4.0.4 on 2023-03-05 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Cotizacion'], [2, 'Sugerencia'], [3, 'Felicitaciones'], [4, 'Reclamo']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id_farmacia', models.AutoField(primary_key=True, serialize=False)),
                ('marca_farmacia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_laboratorio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('gramaje', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('presentacion', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=200)),
                ('fecha_vencimento', models.DateField()),
                ('id_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Principio',
            fields=[
                ('id_principio_activo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_princio_activo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('num_run_usuario', models.CharField(max_length=12)),
                ('nombres_usuario', models.CharField(max_length=100)),
                ('apellido_paterno_usuario', models.CharField(max_length=100)),
                ('appelido_materno_usuario', models.CharField(max_length=100)),
                ('dirreccion_usuario', models.CharField(max_length=150)),
                ('email_usuario', models.EmailField(max_length=254)),
                ('telefono_usuario', models.IntegerField()),
                ('celular_usuario', models.IntegerField()),
                ('whatsapp_usuario', models.IntegerField()),
                ('telegram_usuario', models.IntegerField()),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comuna')),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.provincia')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.region')),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ViaAdminstracion',
            fields=[
                ('id_via_administracion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_via_administracion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioReceta',
            fields=[
                ('id_receta_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('tiempo_tratamiento', models.CharField(max_length=100)),
                ('frecuencia_dosis', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.medicamentos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioFarmacoVigilancia',
            fields=[
                ('id_farmaco', models.AutoField(primary_key=True, serialize=False)),
                ('horario_receta_1', models.CharField(max_length=200)),
                ('horario_receta_2', models.CharField(max_length=200)),
                ('id_receta_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuarioreceta')),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.region'),
        ),
        migrations.CreateModel(
            name='MedicamentosDescuento',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_descuento', models.DateField()),
                ('fecha_termino_descuento', models.DateField()),
                ('descuento_porcentaje', models.IntegerField()),
                ('id_farmacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.farmacia')),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.medicamentos')),
            ],
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='id_principio_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.principio'),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='id_via_administracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.viaadminstracion'),
        ),
        migrations.CreateModel(
            name='FarmaciaSucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_sucursal', models.CharField(max_length=200)),
                ('telefono_sucursal', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comuna')),
                ('id_farmacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.farmacia')),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.provincia')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.region')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.provincia'),
        ),
    ]
